import type { Metadata } from "next";
import "./globals.css";
import NavBarComponent from "@/components/NavBar";
import FooterComponent from "@/components/Footer";
import { Aladin } from '@next/font/google'
import { Suspense } from "react";
import Loader from "@/components/Loader";

const aladin = Aladin({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={aladin.className}>
      <body className=" text-xl md:h-fit">
        <NavBarComponent />
        <Suspense fallback={<Loader />} >
          <main className="">
            {children}
            </main>
        </Suspense>
        <FooterComponent />
      </body>
    </html>
  );
}
